### ISSUE TITLE
Reporte - InterfazTiendita

### ISSUE THREAD

**Issue by KarlaV0** [SistemasTecTlaxiaco/practica-de-visual-studio-KarlaV0#2]
[Unidad1_Topicos_InterfazTiendita.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-visual-studio-KarlaV0/files/6190958/Unidad1_Topicos_InterfazTiendita.pdf)

**Comment by josealfredo79** [comment]
Este reporte de practica le hace falta lista de figuras, tambien objetivo, material, resultados. deben mejorar su trabajo.
